### ISSUE TITLE
Support for formatOnSave after release 1.6.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/vscode-attrs-sorter#14]

**Comment by bartboy011** [comment]
@mrmlnc Did this enhancement ever get released? Formatting on save would be a great improvement.

**Comment by kobvel** [comment]
Any news here?

**Comment by iainhallam** [comment]
Would also like to know this. Putting `attrsSorter.execute` in my `codeActionsOnSave` didn't seem to do much.

**Comment by jd-solanki** [comment]
Anyone managed run it on save??
