### ISSUE TITLE
 Incorrect the behavior if add an event function

### ISSUE THREAD

**Issue by jiangtaste** [mrmlnc/vscode-attrs-sorter#27]
before:
`input(name="files", type="file", onchange='uploadFile()')`

after format
`input(name="files", type="file", onchange='uploadFile()')')`

**Comment by mrmlnc** [comment]
Should be fixed in `master` branch ([test for your case](https://github.com/mrmlnc/vscode-attrs-sorter/blob/master/test/jade.js#L82-L85)). I'll update this plugin today.

**Comment by jiangtaste** [comment]
Tks
