### ISSUE TITLE
on file saves html attributes' case is changed to lowercase

### ISSUE THREAD

**Issue by seishin4real** [mrmlnc/vscode-attrs-sorter#29]
which is bad for writing Angular 2 code where the parser is case-sensitive.

would be nice if there was a setting for this which could be enabled/disabled per workspace.

steps to reproduce:
* `<a routerLink="/home">Home</a>`
* Save file
* the code changes to `<a routerlink="/home">Home</a>`

**Comment by mrmlnc** [comment]
Well, It's not a bug - it's a feature 😄 

Waiting for https://github.com/posthtml/posthtml-parser/pull/15

**Comment by mrmlnc** [comment]
Please look at https://github.com/mrmlnc/vscode-attrs-sorter/releases/tag/2.0.2.
