### ISSUE TITLE
conflict with vscode's original format keybinding: shift-alt-f

### ISSUE THREAD

**Issue by beeplin** [mrmlnc/vscode-attrs-sorter#31]
I like this plugin but it occupies shift-alt-f which is vscode's own shortcuts for formatting files. If even I point "attrsSorter.execute" to another keybinding, shift+alt+f still does not work. 

Is it possbile to change to another keybinding by default? Or how can I restore shift+alt+f  while using this plugin?

THANKS!

**Comment by mrmlnc** [comment]
Hello, @beeplin,

I'm not sure what's going on, but this plugin has no keyboard shortcuts by default.

**Comment by beeplin** [comment]
Oops~ Here is situation:

Without installing this plugin, I can press alt+shift+f to format HTML & Jade files, which is provided by vscode itself;

After installing this plugin, pressing alt+shift+f only resort the attributes for HTML files, no more other formatting.

**Comment by mrmlnc** [comment]
You have 1.10.1 version of VS Code? You can check 1.9.1 (I can, but later)?

**Comment by beeplin** [comment]
yah, I tried 1.8.1 and it's fine. seems it breaks in 1.10.1.

**Comment by mrmlnc** [comment]
You can create issue in VS Code repository?

**Comment by beeplin** [comment]
sure

**Comment by mrmlnc** [comment]
Still broken in 1.10.2?

**Comment by beeplin** [comment]
yes, still conflicts with official formatting.

**Comment by Airkro** [comment]
still unresolved in vscode 1.18.1

**Comment by Aden-git** [comment]
I have the same problem (1.19.2)
