### ISSUE TITLE
Support for `.vue` files (vuejs single file components)

### ISSUE THREAD

**Issue by mubaidr** [mrmlnc/vscode-attrs-sorter#40]
Hi! This extension serves good, can you add support for vuejs single file components?

**Comment by mrmlnc** [comment]
Hello, 

Most likely we must add Vue to list of supported formats, but this is will be work only for components written with HTML syntax.

https://github.com/mrmlnc/vscode-attrs-sorter/blob/master/extension.js#L64

Now you can try to run plugin by F1. If it works, then it's works :)

_Sent from my Xiaomi Redmi Note 4X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mubaidr** [comment]
Ah. never mind, it works with vue files.

**Comment by anyclub** [comment]
press f1 and select attrs-sort it's format 
but not sorting attrs
for win10 vscode1.47.3 plugin2.1.0
